# Turtle Programming In python:

In [3]:
# Changing line color
import turtle
t = turtle.Turtle()
t.pencolor("red")
t.speed(50)

for i in range(50):
    t.forward(100)
    t.left(123)

t.pencolor("blue")
for i in range(100):
    t.forward(100)
    t.left(123)
turtle.done()

In [6]:
# Sqaure of sqaures
t = turtle.Turtle()
t.color("red")

def sqaure(size):
    for i in range(4):
        t.forward(size)
        t.left(90)
sqaure(146)
sqaure(126)
sqaure(96)
sqaure(76)
sqaure(56)
sqaure(36)
sqaure(16)

# Python Statistics Module:
- You Can calculate mathematical statistics of numerical data
- Mean
- Median 
- Mode
- varience

In [7]:
import statistics as st
l = list(range(1,21))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [9]:
# Mean
print(st.mean(l))
print(sum(l)/len(l))

10.5
10.5


In [10]:
# Median --> returns middle value of numerical data
print(st.median([1,2,3,4,5]))

3


In [11]:
# Mode: returns the most common data point
print(st.mode([1,2,1,2,2,5,4,7,9,2,6]))

2


In [13]:
# varienace:
print(st.variance(l))

35.0


# Random Module:
- used for to get random numbers

In [17]:
import random as rd
# Random method
rd.random()

0.010572684003420263

In [22]:
# randint() - return a random numbers between given range of numbers
print(rd.randint(1,11))
print(rd.randint(1,100))


3
59


In [31]:
# Randrange() 
print(rd.randrange(1,10))
print(rd.randrange(1,10,2))
print(rd.randrange(1,100,10))


5
7
61


In [38]:
# choice method:
l = [1,2,3,4,5]
print(rd.choice(l))
print(rd.choices(l,k =3))

5
[1, 4, 2]


In [43]:
# Shuffle
l = [1,2,3,4,5]
rd.shuffle(l)
print(l)

[1, 3, 4, 5, 2]


# Numpy Module:
- Numpy module is used to for working with arrays
- Numpy stands for numerical python


In [2]:
import numpy as np
l = [1,2,3,4,4,5,6]
arr = np.array(l)
print(arr)
print(type(arr))

[1 2 3 4 4 5 6]
<class 'numpy.ndarray'>


In [3]:
l = list(range(1,21))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [5]:
arr2 =np.arange(1,21)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Dimensions in Arrays


In [6]:
# 1- D
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
# 2 -D
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
# 3 - d
arr2 = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(arr2)

[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
